apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-detection-deployment
  labels:
    app: spam-detection
spec:
  replicas: 3  # Number of instances of the application to deploy
  selector:
    matchLabels:
      app: spam-detection
  template:
    metadata:
      labels:
        app: spam-detection
    spec:
      containers:
      - name: spam-detection
        image: manuagasimani/django-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        # Add any additional environment variables, such as database credentials
 
